FIND_PATH(
    FECAPI_INCLUDE_DIRS
    NAMES fec/fec_api.h
    HINTS $ENV{FECAPI_DIR}/include ${CMAKE_INSTALL_PREFIX}/include
    PATHS /usr/local/include /usr/include
)


FIND_LIBRARY(
    GEN_FECAPI_LIBRARIES
    NAMES fec 
    HINTS $ENV{FECAPI_DIR}/lib ${CMAKE_INSTALL_PREFIX}/lib
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

FIND_LIBRARY(
    GR_FECAPI_LIBRARIES
    NAMES gr-fec 
    HINTS $ENV{FECAPI_DIR}/lib ${CMAKE_INSTALL_PREFIX}/lib
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

LIST(APPEND FECAPI_LIBRARIES ${GEN_FECAPI_LIBRARIES})
IF(NOT ${GR_FECAPI_LIBRARIES} STREQUAL "GR_FECAPI_LIBRARIES-NOTFOUND")
    LIST(APPEND FECAPI_LIBRARIES ${GR_FECAPI_LIBRARIES})
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FECAPI DEFAULT_MSG FECAPI_LIBRARIES FECAPI_INCLUDE_DIRS)
MARK_AS_ADVANCED(FECAPI_LIBRARIES FECAPI_INCLUDE_DIRS)
